analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3568243,"name"\:"Cellphone Shop Trial \#3568243","teamId"\:3583113,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3554200,"accountId"\:null,"autoIntegrate"\:false,"sampleProject"\:false}
analytics.team={"id"\:3583113,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
analytics.testreport.autoupload.manualstop.enable=false
