<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>vkowshik007@gmail.com;</mailRecipient>
   <maxConcurrentInstances>1</maxConcurrentInstances>
   <numberOfRerun>3</numberOfRerun>
   <orchestration>CLASSIC</orchestration>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c61bc5a4-702d-4f90-98f0-e3fdd1513981</testSuiteGuid>
   <testCaseLink>
      <guid>4be32308-7779-481f-90fc-d5e79e218672</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Private Access Click</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3d7d51fa-d39a-4d8c-8161-968935c35b50</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3d7d51fa-d39a-4d8c-8161-968935c35b50</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>abc10f70-6516-4610-bed4-f63d4e3dae14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3d7d51fa-d39a-4d8c-8161-968935c35b50</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>5bb6b3c6-0064-4c0c-82de-1df8d40604c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f9e4b273-4a12-42f6-be33-9a15c2e8b221</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SSNMART_LOGIN_001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f41b838-56f0-41af-8787-3bdf7da7d612</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>895202c2-5b1c-4145-9f03-e938f0a68dec</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
