<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_WEALTH</name>
   <tag></tag>
   <elementGuidId>9f1d0990-ddb4-46f9-b141-46947d851491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(name() = 'div') and (position() = 2)]/*[(name() = 'div') and (position() = 5)]//div//div//div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-child(2) > div:nth-child(5) div div div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;WEALTH&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bd6b1bc6-3b6d-4a74-a923-727fd071b88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Navigation---typeName---3H3nF</value>
      <webElementGuid>e97344e3-6435-46fc-826f-b25d0228291f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WEALTH</value>
      <webElementGuid>2a88109b-7dcc-4ad6-b6fb-4ecb776f6e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-47b9414925f88ad376d38821dec72c93</value>
      <webElementGuid>84c1e9e6-f517-4fde-b9fd-a270def4535d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'div') and (position() = 2)]/*[(name() = 'div') and (position() = 5)]//div//div//div</value>
      <webElementGuid>47b72158-6325-4f0f-86d7-736e138a133a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'div') and (position() = 2)]/*[(name() = 'div') and (position() = 5)]//div//div//div</value>
      <webElementGuid>9ac9ddb1-e38f-4414-bbba-e7f20a6d473c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'WEALTH' or . = 'WEALTH')]</value>
      <webElementGuid>2d5c3787-2855-4424-980e-6be035c31361</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
